# Generated by Django 5.1.4 on 2024-12-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "results",
                    models.ImageField(
                        help_text="upload your result",
                        upload_to="images/results/",
                        verbose_name="before/after",
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        auto_now_add=True,
                        help_text="add the date",
                        verbose_name="date added",
                    ),
                ),
                (
                    "result_is_published",
                    models.BooleanField(
                        default=True,
                        help_text="is this image posted?",
                        verbose_name="image is posted",
                    ),
                ),
            ],
            options={
                "verbose_name": "gallery_photo",
                "verbose_name_plural": "gallery_photos",
            },
        ),
    ]
