# Generated by Django 5.1.4 on 2024-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="enter your subject",
                        max_length=50,
                        verbose_name="subject",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="enter your text", verbose_name="text"),
                ),
            ],
            options={
                "verbose_name": "feedback",
                "verbose_name_plural": "feedbacks",
            },
        ),
    ]
