# Generated by Django 5.1.4 on 2025-01-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_description", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("is_visible_on_main", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
