# Generated by Django 5.1.4 on 2025-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "review", "verbose_name_plural": "reviews"},
        ),
        migrations.AddField(
            model_name="review",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="review",
            name="source",
            field=models.ImageField(
                blank=True,
                help_text="upload an image of source",
                upload_to="images/review_sources/",
                verbose_name="source image",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="source_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
