# Generated by Django 5.1.4 on 2024-12-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_title",
                    models.CharField(
                        help_text="input service name",
                        max_length=20,
                        verbose_name="service title",
                    ),
                ),
                (
                    "service_description",
                    models.TextField(
                        help_text="input service deescription",
                        verbose_name="service description",
                    ),
                ),
                (
                    "service_thumbnail",
                    models.ImageField(
                        help_text="upload an image",
                        upload_to="images/service_thumbnails/",
                        verbose_name="service image",
                    ),
                ),
                (
                    "service_price",
                    models.PositiveIntegerField(
                        help_text="enter service average price",
                        verbose_name="service price",
                    ),
                ),
                (
                    "service_is_published",
                    models.BooleanField(
                        help_text="is this service published?",
                        verbose_name="is published",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
    ]
