# Generated by Django 5.1.4 on 2025-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_coefficient",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="little decimal number",
                max_digits=5,
                verbose_name="coefficient of service",
            ),
        ),
    ]
