# Generated by Django 5.1.4 on 2025-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_service_service_coefficient"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_included",
            field=models.TextField(
                default="everything that you need)",
                help_text="what does this service include",
                max_length=100,
                verbose_name="service included",
            ),
        ),
    ]
