# Generated by Django 5.1.4 on 2025-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_service_service_included"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_title",
                    models.CharField(
                        help_text="input extra name",
                        max_length=20,
                        verbose_name="extra title",
                    ),
                ),
                (
                    "extra_price",
                    models.PositiveIntegerField(
                        help_text="enter price for this extra",
                        verbose_name="extra price",
                    ),
                ),
                (
                    "extra_thumbnail",
                    models.ImageField(
                        help_text="upload an image",
                        upload_to="images/extra_thumbnails/",
                        verbose_name="extra image",
                    ),
                ),
            ],
        ),
    ]
