# Generated by Django 5.1.4 on 2025-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_service_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
