# Generated by Django 5.1.4 on 2025-08-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.FileField(upload_to="service_icons/")),
                ("text", models.CharField(blank=True, max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icons",
                        to="catalog.service",
                    ),
                ),
            ],
        ),
    ]
