# Generated by Django 5.1.4 on 2025-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_serviceicon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceicon",
            name="icon",
        ),
        migrations.AddField(
            model_name="serviceicon",
            name="svg_code",
            field=models.TextField(default="pipikaka", help_text="Вставь сюда код SVG"),
        ),
    ]
