# Generated by Django 5.1.4 on 2025-07-28 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("date", models.DateField(verbose_name="Дата уборки")),
                ("time", models.TimeField(verbose_name="Время уборки")),
                ("message", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="CleaningOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.PositiveIntegerField(
                        verbose_name="Площадь (в квадратных футах)"
                    ),
                ),
                ("carpet_area", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("townhouse", "Townhouse"),
                            ("office", "Office"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_rooms", models.PositiveIntegerField()),
                ("num_bathrooms", models.PositiveIntegerField()),
                ("windows", models.BooleanField(default=False)),
                ("sills", models.BooleanField(default=False)),
                ("cabinets", models.BooleanField(default=False)),
                ("fridge", models.BooleanField(default=False)),
                ("oven", models.BooleanField(default=False)),
                ("microwave", models.BooleanField(default=False)),
                ("dishwasher", models.BooleanField(default=False)),
                ("terrace", models.BooleanField(default=False)),
                ("blinds", models.BooleanField(default=False)),
                ("carpet", models.BooleanField(default=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standart"),
                            ("deep", "Deep"),
                            ("moving", "Move in/out"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "One-time"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
