# Generated by Django 5.1.4 on 2025-07-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_service_slug"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cleaningorder",
            name="blinds",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="cabinets",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="carpet",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="dishwasher",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="fridge",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="microwave",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="oven",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="sills",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="terrace",
        ),
        migrations.RemoveField(
            model_name="cleaningorder",
            name="windows",
        ),
        migrations.AddField(
            model_name="cleaningorder",
            name="extras",
            field=models.ManyToManyField(blank=True, to="catalog.extra"),
        ),
        migrations.AlterField(
            model_name="cleaningorder",
            name="service_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.service",
                verbose_name="Service Type",
            ),
        ),
    ]
