# Generated by Django 5.1.4 on 2025-07-31 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_service_slug"),
        ("order", "0004_alter_cleaningorder_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaningorder",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.service",
                verbose_name="Service Type",
            ),
        ),
    ]
