# Generated by Django 5.1.4 on 2025-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_cleaningorder_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningorder",
            name="carpet",
            field=models.BooleanField(default=False),
        ),
    ]
